### ISSUE TITLE
Refactor the Code

### ISSUE THREAD

**Issue by kamransarwar** [kamransarwar/QuizApp#1]

**Comment by kgoel085** [comment]
What main refactoring are u aiming to have ??

**Comment by anuk79** [comment]
@kamransarwar Hi, what kind of refactoring are you looking for? Are there any specific files that I can pick up to refactor? Let me know, I am willing to contribute

**Comment by kamransarwar** [comment]
HI @anuk79 and @kgoel085, 

This app is currently deployed to Heroku for testing. You can browse the app by following link:
http://quiztime2.herokuapp.com

You can improve the code in following file to generate the quiz result [That isn't working right now].
https://github.com/kamransarwar/QuizApp/blob/master/controllers/quizApis.js

or you can pick any file from controller folder and improve the application APIs.
https://github.com/kamransarwar/QuizApp/tree/master/controllers

or you can also work on views in public folder to improve the UI of application.
https://github.com/kamransarwar/QuizApp/tree/master/public

Thanks
@kamransarwar

**Comment by kgoel085** [comment]
@anuk79 @kamransarwar i like to start with the controller folders to refactor it. If it is ok to all

**Comment by kamransarwar** [comment]
@kgoel085, please work on it. Thanks

**Comment by kgoel085** [comment]
@kamransarwar i m on it. So should i just fork it and create a new branch or is there any approach i have to follow for this ??

**Comment by kgoel085** [comment]
@kamransarwar i m installing ur app locally and most of the modules used in ur app are deprecated and are much past the current versions. SO what would u suggest still refactor or use ur logic to create a fresh project with all updated dependencies ??. I just have this idea as refactoring will also make us dig the code. SO, if you have time just to help us. we may create a new app from scracth with updated code base

**Comment by kgoel085** [comment]
![image](https://user-images.githubusercontent.com/38721303/67624711-c56ff900-f851-11e9-95ac-b3a07c60192d.png)
 
Please see this screenshot. It is critical to make a decision here regarding the dependencies

**Comment by kamransarwar** [comment]
@kgoel085 fork repo. create new branch. if there is need to update dependencies please update. Thanks

**Comment by kgoel085** [comment]
@kamransarwar on it

**Comment by kgoel085** [comment]
@kamransarwar so it is mixture of node & angular app mixed together right ?

**Comment by kamransarwar** [comment]
@kgoel085 This is a MEAN Stack app. Yes, front end is written in Angular, back end is written in Node and app uses MongoDB to store the data.

**Comment by kgoel085** [comment]
@kamransarwar so the UI shown in the app on the test site is angularas the package functionalities  used in the code are not visible on the UI. So, are not on the site or are not being used yet like passport and twillio stripe etc

**Comment by kgoel085** [comment]
@kamransarwar have u checked ur config files ? Please give it a check though

**Comment by kgoel085** [comment]
@kamransarwar ur backend is all messed up. Even your crypto lib is all broken up along with all the session handlers. I would really suggest you to review and make this app from start as refactoring it from scratch along with adding and removing packages in order to make app work with latest technologies is more work than creating it from scratch as you have all the logic. It will be more easy

**Comment by kgoel085** [comment]
@kamransarwar i m still trying to refactor app.js first as it is all messed up together like all routes, controllers, middlewares all are placed in one place. We have to refactor it first in order for other to setup app on their local systems

**Comment by kamransarwar** [comment]
@kgoel085 I can understand because I build this app 2 or 3 years ago. Most of the app dependencies are out of date. If you can upgrade the dependencies to new version that would be awesome. Please do refactoring of code in App.js. If you think you need to write new routes and middleware please write them. I'll consider this refactoring too.

**Comment by kgoel085** [comment]
@kamransarwar please do give a check to ur creds in config folder please. i think changes are required their immediately by you

**Comment by kamransarwar** [comment]
@kgoel085 I think my app only uses the MongoDB cred from config folder, that is only for local environment. All other cred were for passport.js but I didn't setup passport (user sign up and user login) in my app. You can ignore them.

**Comment by kgoel085** [comment]
@kamransarwar i got that but please make sure ur passport provider credentials that are saved in the file are not ur actual personal account credentails that is what i m more concerned about here.

**Comment by kamransarwar** [comment]
@kgoel085 they aren't mine real credentials. Thank you for looking at them.

**Comment by kgoel085** [comment]
@kamransarwar no problem man

**Comment by kgoel085** [comment]
@kamransarwar Hi, i have made changes to app.js which made app to work. Please check this branch of my forked branch and if it is ok to push. Please tell me. It's still a work in progress. 

https://github.com/kgoel085/QuizApp/tree/refactor

**Comment by kgoel085** [comment]
@kamransarwar i have implemented the common routes like index and test route but only one left are the user auth and passport routes which i m not sure whether are they currently in work or not. Please see my commits as i have made the app in working state but jade is having some issues

**Comment by kgoel085** [comment]
@kamransarwar added a pull request. I have refactored enough so that app can be started on the local system

**Comment by kamransarwar** [comment]
@kgoel085 I'll review your changes and merge them to base version. Thanks
